import type { Metadata } from "next";
import Link from "next/link";
import { Zap } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "QuickLearn Terms of Service and conditions of use.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b">
        <div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2 font-semibold">
            <Zap className="size-5 text-primary" />
            QuickLearn
          </Link>
          <Link
            href="/"
            className="text-sm text-muted-foreground hover:text-foreground"
          >
            Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 sm:py-16">
        <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-muted-foreground">
          Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
        </p>

        <div className="prose prose-neutral dark:prose-invert mt-10 max-w-none">
          <section className="mb-10">
            <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              By accessing or using QuickLearn (&quot;the Service&quot;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">2. Description of Service</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              QuickLearn is an AI-powered learning platform that helps you transform content (PDFs, videos, links, audio)
              into summaries, flashcards, quizzes, and interactive study materials. Features and availability may vary
              by plan and region.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">3. Account and Registration</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              You must provide accurate information when creating an account. You are responsible for keeping your
              credentials secure and for all activity under your account. You must be at least 13 years old (or the
              minimum age in your jurisdiction) to use the Service.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">4. Acceptable Use</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              You agree not to use the Service for any illegal purpose, to violate any laws, or to infringe the rights
              of others. You may not attempt to gain unauthorized access to the Service or other users&apos; accounts,
              or use the Service to distribute malware or spam. We may suspend or terminate accounts that violate these
              terms.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">5. Content and Intellectual Property</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              You retain ownership of content you upload. By using the Service, you grant us a limited license to
              process and store your content to provide the Service. QuickLearn&apos;s branding, software, and materials
              are our intellectual property and may not be copied or used without permission.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">6. Subscriptions and Payments</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              Paid plans are billed according to the pricing at the time of purchase. You may cancel at any time;
              cancellation will take effect at the end of the current billing period. Refunds are handled according to
              our refund policy and applicable law.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">7. Disclaimers</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              The Service is provided &quot;as is.&quot; We do not guarantee accuracy of AI-generated content. You use
              the Service at your own risk. We are not liable for decisions made based on content generated by the
              Service.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">8. Limitation of Liability</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, QuickLearn and its affiliates shall not be liable for any
              indirect, incidental, special, or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">9. Changes</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              We may update these Terms from time to time. We will notify you of material changes by posting the new
              Terms and updating the &quot;Last updated&quot; date. Continued use of the Service after changes
              constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-semibold">10. Contact</h2>
            <p className="mt-2 text-muted-foreground leading-relaxed">
              For questions about these Terms, please contact us through the feedback or support options in the app,
              or at the contact details provided on our website.
            </p>
          </section>
        </div>

        <p className="mt-12 text-sm text-muted-foreground">
          <Link href="/" className="underline hover:text-foreground">
            Return to QuickLearn
          </Link>
          {" · "}
          <Link href="/privacy" className="underline hover:text-foreground">
            Privacy Policy
          </Link>
        </p>
      </main>
    </div>
  );
}
